import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'ko' | 'ja' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.livetrading': 'Live Trading',
    'nav.analytics': 'Analytics', 
    'nav.alerts': 'Alerts',
    'nav.search': 'Search',
    'nav.ranking': 'Top Stocks',
    'nav.settings': 'Settings',
    
    // Dashboard
    'dashboard.title': 'InsiderTrack Pro',
    'dashboard.subtitle': 'AI-Powered Insider Trading Monitor',
    'dashboard.lastUpdated': 'Last updated',
    'dashboard.stats.todayTrades': 'Today\'s Trades',
    'dashboard.stats.totalVolume': 'Total Volume',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.marketCoverage': 'Market Coverage',
    'dashboard.topMoversToday': 'Top Movers Today',
    
    // Trades
    'trades.loadingStats': 'Loading trading statistics...',
    'trades.failedStats': 'Failed to load trading statistics. Please refresh the page.',
    'trades.recentTrades': 'Recent Insider Trades',
    'trades.loadingTrades': 'Loading trades...',
    'trades.viewDetails': 'View Details',
    'trades.loadMore': 'Load More Trades',
    'trades.noTrades': 'No trades available',
    'trades.company': 'Company',
    'trades.shares': 'Shares',
    'trades.price': 'Price',
    'trades.total': 'Total Value',
    'trades.signal': 'Signal',
    'trades.significance': 'Significance',
    'trades.filed': 'Filed',
    
    // Settings
    'settings.title': 'Settings',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.notifications': 'Notifications',
    'settings.language.english': 'English',
    'settings.language.korean': '한국어',
    'settings.language.japanese': '日本語',
    'settings.language.chinese': '中文',
    'settings.theme.light': 'Light',
    'settings.theme.dark': 'Dark',
    'settings.theme.system': 'System',
    'settings.description': 'Manage your application preferences and settings.',
    'settings.themeDescription': 'Choose your preferred theme',
    'settings.notificationsFuture': 'Notification settings will be available in a future update.',
    
    // WebSocket Status
    'websocket.connected': 'Connected to live feed',
    'websocket.disconnected': 'Disconnected from live feed',
    'websocket.connecting': 'Connecting to live feed...',
    
    // General
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.refresh': 'Refresh',
    'general.save': 'Save',
    'general.cancel': 'Cancel',
    'general.delete': 'Delete',
    
    // Page specific
    'page.dashboard.subtitle': 'Real-time insider trading monitoring and market intelligence',
    'page.livetrading.title': 'Live Trading',
    'page.livetrading.subtitle': 'Real-time insider trading activity with AI-powered analysis',
    'page.search.placeholder': 'Search companies, tickers, traders, or titles...',
    'page.alerts.title': 'Smart Alerts',
    'page.alerts.subtitle': 'Set up intelligent alerts for insider trading activity',
    'page.analytics.title': 'Market Analytics',
    'page.analytics.subtitle': 'Comprehensive analysis of insider trading patterns',
    
    // WebSocket and Connection
    'connection.liveFeedActive': 'Live data feed active - Real-time SEC filing monitoring',
    'connection.connectionLost': 'Connection lost - Attempting to reconnect...',
    'connection.liveFeed': 'Live Feed',
    'connection.disconnected': 'Disconnected',
    
    // Statistics and Data
    'stats.todayTrades': 'Today\'s Trades',
    'stats.totalVolume': 'Total Volume',
    'stats.tradingSummary': 'Trading Summary',
    'stats.failedLoad': 'Failed to load trading statistics. Please refresh the page.',
    'stats.fromLastWeek': 'from last week',
    
    // Filters and Search
    'filter.allTypes': 'All Types',
    'filter.buyOrders': 'Buy Orders',
    'filter.sellOrders': 'Sell Orders',
    'filter.allSignals': 'All Signals',
    'filter.buySignal': 'Buy Signal',
    'filter.sellSignal': 'Sell Signal',
    'filter.holdSignal': 'Hold Signal',
    'filter.buyOnly': 'Buy Only',
    'filter.sellOnly': 'Sell Only',
    
    // Placeholders
    'placeholder.searchCompany': 'Search company...',
    'placeholder.searchTrader': 'Search trader...',
    'placeholder.noLimit': 'No limit',
    'placeholder.preferredLanguage': 'Choose your preferred language',
    
    // Alert types
    'alerts.type.volume': 'Trade Volume',
    'alerts.type.company': 'Company Name',
    'alerts.type.trader': 'Trader Title',
    
    // Search page
    'search.title': 'Search & Filter',
    'search.subtitle': 'Search and filter insider trading data with advanced criteria',
    'search.filters': 'Filters',
    'search.clear': 'Clear',
    'search.tradeType': 'Trade Type',
    'search.dateRange': 'Date Range',
    'search.sortBy': 'Sort By',
    'search.dateRange.all': 'All Time',
    'search.dateRange.7d': 'Last 7 days',
    'search.dateRange.30d': 'Last 30 days',
    'search.dateRange.90d': 'Last 90 days',
    'search.sort.recent': 'Most Recent',
    'search.sort.value': 'Highest Value',
    'search.sort.company': 'Company Name',
    'search.results': 'Results',
    'search.buyTrades': 'Buy Trades',
    'search.sellTrades': 'Sell Trades',
    'search.totalVolume': 'Total Volume',
    'search.companies': 'Companies',
    'search.traders': 'Traders',
    'search.totalFound': 'Total trades found',
    'search.combinedValue': 'Combined value',
    'search.uniqueEntities': 'Unique entities',
    'search.uniqueInsiders': 'Unique insiders',
    'search.searchResults': 'Search Results',
    'search.noTrades': 'No trades found',
    'search.placeholder.minValue': '1000000',
    'search.value': 'Min Value',
    
    // Alerts page
    'alerts.title': 'Smart Alerts',
    'alerts.subtitle': 'Set up intelligent alerts for insider trading activity',
    'alerts.active': 'Active Alerts',
    'alerts.createNew': 'Create New Alert',
    'alerts.alertName': 'Alert Name',
    'alerts.alertType': 'Alert Type',
    'alerts.condition': 'Condition',
    'alerts.value': 'Value',
    'alerts.paused': 'Paused',
    'alerts.noAlerts': 'No alerts configured yet',
    'alerts.createFirst': 'Create your first alert below',
    'alerts.noMatches': 'No recent matches',
    'alerts.setupMatches': 'Set up alerts to see matches here',
    'alerts.condition.greaterThan': 'Greater than',
    'alerts.condition.lessThan': 'Less than',
    'alerts.condition.equals': 'Equals',
    'alerts.condition.contains': 'Contains',
    'alerts.placeholder.name': 'e.g., Large Apple Trades',
    'alerts.recentMatches': 'Recent Matches',
    
    // Live Trading page
    'liveTrading.filtersAndSearch': 'Filters & Search',
    'liveTrading.tradeType': 'Trade Type',
    'liveTrading.aiSignal': 'AI Signal',
    'liveTrading.companyTicker': 'Company/Ticker',
    'liveTrading.traderName': 'Trader Name',
    'liveTrading.minValue': 'Min Value ($)',
    'liveTrading.maxValue': 'Max Value ($)',
    'liveTrading.liveFeed': 'Live Trading Feed',
    'liveTrading.tradesShown': 'trades shown',
    'liveTrading.noTrades': 'No trades found',
    'liveTrading.adjustFilters': 'Try adjusting your filters',
    'liveTrading.insider': 'Insider',
    'liveTrading.tradeDetails': 'Trade Details',
    'liveTrading.totalValue': 'Total Value',
    'liveTrading.score': 'Score:',
    'liveTrading.loadMore': 'Load More Trades',
    'liveTrading.activeNow': 'Active Now',
    'liveTrading.alertsSet': 'Alerts Set',
    'liveTrading.pageTitle': 'All Trades Display & Search',
    'liveTrading.pageTitleMobile': 'Trade Search',
    'liveTrading.pageSubtitle': 'Search and filter all insider trading data',
    'liveTrading.totalTrades': 'Total',
    'liveTrading.filtered': 'Filtered',
    'liveTrading.realtimeStock': 'Real-time stock prices',
    'liveTrading.loaded': 'loaded',
    'liveTrading.loading': 'loading',
    'liveTrading.dataQuality': 'Data Quality',
    'liveTrading.issues': 'issues',
    'liveTrading.loadingTrades': 'Loading trade data...',
    'liveTrading.alert': 'Alert',
    'liveTrading.watchlist': 'Watchlist',
    'liveTrading.added': 'Added',
    'liveTrading.watch': 'Watch',
    'liveTrading.advancedAiAnalysis': 'Advanced AI Analysis',
    'liveTrading.confidenceLevel': 'Confidence Level',
    'liveTrading.advancedAnalyzing': 'Advanced AI analysis in progress...',
    'liveTrading.realtimePriceInfo': 'Real-time Price Information',
    'liveTrading.insiderTradePrice': 'Insider Trade Price',
    'liveTrading.expectedImpact': 'Expected Impact',
    'liveTrading.similarTrades': 'Similar Trades',
    'liveTrading.count': 'count',
    'liveTrading.pieces': 'pieces',
    'liveTrading.analysisInProgress': 'Analyzing news, financial data, and insider patterns comprehensively',
    'liveTrading.basicAnalysis': 'Basic Analysis',
    'liveTrading.loadingTradeData': 'Loading trade data...',
    'liveTrading.fetchingLatestInsider': 'Fetching latest insider trading information',
    'liveTrading.avgLoadingTime': '💡 Average loading time: 3-5 seconds',
    'liveTrading.remaining': 'remaining',
    'liveTrading.myWatchlist': 'My Watchlist',
    'liveTrading.addToWatchlist': 'Add to Watchlist',
    'liveTrading.alertSettings': 'Alert Settings',
    'liveTrading.emailAlerts': 'Email Alerts',
    'liveTrading.smartAlerts': 'Smart Alerts',
    'liveTrading.watchlistAdded': 'Added to Watchlist',
    'liveTrading.realtimeAlertsAvailable': 'Real-time alerts are also available',
    'liveTrading.getRealtimeAlerts': 'Get real-time trading alerts',
    'liveTrading.alertEmail': 'Alert Email',
    'liveTrading.alertConditions': 'Alert Conditions',
    'liveTrading.successfullyAdded': 'Successfully added!',
    'liveTrading.additionComplete': 'Addition Complete!',
    'liveTrading.canViewSeparately': 'You can now view insider trading information separately',
    'liveTrading.viewWatchlist': 'View Watchlist',
    'liveTrading.whenInsiderTrade': 'When insider trade occurs',
    'liveTrading.whenPriceChange': 'When significant price change',
    'liveTrading.whenVolumeSpike': 'When trading volume spikes',
    'liveTrading.largeTrades': 'Large trades ($10M+)',
    'liveTrading.whenRecommendedPrice': 'When recommended buy price is reached',
    'liveTrading.dataQualityReport': 'Data Quality Report',
    'liveTrading.validTrades': 'Valid Trades',
    'liveTrading.insiderBuyPrice': 'Insider Buy Price',
    'liveTrading.insiderSellPrice': 'Insider Sell Price',
    'liveTrading.avgInsiderBuyPrice': 'Average Insider Buy Price',
    'liveTrading.aiRecommendedBuyPrice': 'AI Recommended Buy Price',
    'liveTrading.currentPrice': 'Current Price',
    'liveTrading.updated': 'Updated',
    'liveTrading.opportunityAfterSell': 'Opportunity after insider sell',
    'liveTrading.keyFindings': 'Key Findings',
    'liveTrading.aiTargetPrice': 'AI Target Price',
    'liveTrading.conservative': 'Conservative',
    'liveTrading.realistic': 'Realistic',
    'liveTrading.optimistic': 'Optimistic',
    'liveTrading.actionableRecommendation': 'Actionable Recommendation',
    'liveTrading.catalystsIdentified': 'Catalysts identified',
    'liveTrading.follow': 'Follow',
    'liveTrading.opportunistic': 'Opportunistic',
    
    // Trade Card
    'tradeCard.filed': 'Filed',
    'tradeCard.shares': 'Shares',
    'tradeCard.avgPrice': 'Avg Price',
    'tradeCard.totalValue': 'Total Value',
    'tradeCard.ownership': 'ownership',
    'tradeCard.details': 'Details',
    
    // Trade List
    'tradeList.recentTrades': 'Recent Insider Trades',
    'tradeList.searchCompanies': 'Search companies...',
    'tradeList.sort': 'Sort:',
    'tradeList.date': 'Date',
    'tradeList.value': 'Value',
    'tradeList.noTradesFound': 'No trades found matching your criteria.',
    'tradeList.loading': 'Loading...',
    'tradeList.loadMore': 'Load More Trades',
    'tradeList.noMatches': 'No trades found matching your criteria.',
    'tradeList.searchPlaceholder': 'Search companies...',
    
    // Dashboard Stats
    'dashboardStats.todayTrades': "Today's Trades",
    'dashboardStats.totalVolume': 'Total Volume',
    'dashboardStats.fromLastWeek': 'from last week',
    'dashboardStats.recentActivity': 'Recent Activity',
    'dashboardStats.monitoring': 'Monitoring insider trades across all major exchanges',
    'dashboardStats.marketCoverage': 'Market Coverage',
    'dashboardStats.realTimeAnalysis': 'Real-time SEC filing analysis and trade classification',
    'dashboardStats.topMovers': 'Top Movers Today',
    
    // Analytics page
    'analytics.subtitle': 'Comprehensive insider trading market analysis and insights',
    'analytics.totalTrades': 'Total Trades',
    'analytics.transactionsRecorded': 'Insider transactions recorded',
    'analytics.totalVolume': 'Total Volume',
    'analytics.combinedValue': 'Combined transaction value',
    'analytics.avgTradeSize': 'Avg Trade Size',
    'analytics.averageValue': 'Average transaction value',
    'analytics.companies': 'Companies',
    'analytics.uniqueTracked': 'Unique companies tracked',
    'analytics.tradeDistribution': 'Trade Type Distribution',
    'analytics.monthlyActivity': 'Monthly Trading Activity',
    'analytics.topCompanies': 'Top Companies by Trading Volume',
    'analytics.trades': 'trades',
    'analytics.combinedTransactionValue': 'Combined transaction value',
    'analytics.averageTransactionValue': 'Average transaction value',
    'analytics.uniqueCompaniesTracked': 'Unique companies tracked',
    'analytics.tradeTypeDistribution': 'Trade Type Distribution',
    'analytics.monthlyTradingActivity': 'Monthly Trading Activity',
    'analytics.topCompaniesByVolume': 'Top Companies by Trading Volume',
    'analytics.buys': 'Buys',
    'analytics.sells': 'Sells',
    
    // Trade Detail page
    'tradeDetail.notFound': 'Trade Not Found',
    'tradeDetail.notFoundMessage': 'The requested trade could not be found.',
    'tradeDetail.backToDashboard': 'Back to Dashboard',
    'tradeDetail.back': 'Back',
    'tradeDetail.title': 'Trade Details',
    'tradeDetail.companyInfo': 'Company Information',
    'tradeDetail.company': 'Company',
    'tradeDetail.tickerSymbol': 'Ticker Symbol',
    'tradeDetail.tradeType': 'Trade Type',
    'tradeDetail.traderInfo': 'Trader Information',
    'tradeDetail.name': 'Name',
    'tradeDetail.titlePosition': 'Title/Position',
    'tradeDetail.ownership': 'Ownership',
    'tradeDetail.transactionDetails': 'Transaction Details',
    'tradeDetail.sharesTraded': 'Shares Traded',
    'tradeDetail.pricePerShare': 'Price per Share',
    'tradeDetail.totalValue': 'Total Transaction Value',
    'tradeDetail.filingDate': 'Filing Date',
    'tradeDetail.currentPrice': 'Current Stock Price',
    'tradeDetail.volume': 'Volume',
    'tradeDetail.lastUpdated': 'Last Updated',
    'tradeDetail.analysis': 'Detailed Analysis',
    'tradeDetail.priceComparison': 'Price Comparison',
    'tradeDetail.tradePrice': 'Trade Price:',
    'tradeDetail.currentPriceLabel': 'Current Price:',
    'tradeDetail.perShareComparison': 'Per share comparison',
    'tradeDetail.secFiling': 'SEC Filing #',
    'tradeDetail.totalTransactionValue': 'Total Transaction Value',
    'tradeDetail.currentStockPrice': 'Current Stock Price',
    'tradeDetail.detailedAnalysis': 'Detailed Analysis',
    'tradeDetail.actualTradePrice': 'Actual Trade Price',
    'tradeDetail.insiderAvgPrice': 'Insider Average Price',
    'tradeDetail.last30DaysAvg': 'Last 30 days average',
    'tradeDetail.sameTicker': 'Same ticker average',
    'tradeDetail.currentMarketPrice': 'Current Market Price',
    'tradeDetail.realtimeEstimate': 'Real-time estimate',
    'tradeDetail.marketClosed': 'Market closed (last price)',
    'tradeDetail.realtimePrice': 'Real-time price',
    'tradeDetail.lastClosePrice': 'Last close price (market closed)',
    'tradeDetail.aiAnalysisResults': 'AI Analysis Results',
    'tradeDetail.tradingPatternAnalysis': 'Trading Pattern Analysis',
    'tradeDetail.investmentStrategy': 'Investment Strategy',
    'tradeDetail.additionalInsights': 'Additional Insights',
    
    // Price Comparison Chart
    'priceChart.title': 'Price Comparison Chart',
    'priceChart.tradePrice': 'Trade Price',
    'priceChart.currentPrice': 'Current Price',
    'priceChart.today': 'Today',
    'priceChart.insiderTrade': 'INSIDER TRADE',
    'priceChart.movement': 'Price Movement Since Trade',
    'priceChart.increased': 'Price Increased',
    'priceChart.decreased': 'Price Decreased',
    'priceChart.tradePriceLabel': 'Trade Price:',
    'priceChart.currentLabel': 'Current:',
    
    // Ranking page
    'ranking.title': 'Top Buy Recommendations',
    'ranking.subtitle': 'AI-powered stock recommendations based on insider trading patterns',
    'ranking.topStocks': 'Top 10 Recommended Stocks',
    'ranking.recommendation': 'Recommendation',
    'ranking.buyPotential': 'Buy Potential',
    'ranking.marketCap': 'Market Cap',
    'ranking.volume': 'Volume',
    'ranking.priceChange': 'Price Change',
    'ranking.lastPrice': 'Current Price',
    'ranking.strongBuy': 'Strong Buy',
    'ranking.buy': 'Buy',
    'ranking.hold': 'Hold',
    'ranking.analysis': 'Analysis',
    'ranking.insiderActivity': 'Insider Activity',
    'ranking.tradesLast30Days': 'trades in last 30 days',
    'ranking.avgTradeValue': 'Avg Trade Value',
    'ranking.netBuying': 'Net Buying',
    'ranking.loading': 'Loading stock rankings...',
    'ranking.noData': 'No ranking data available',
    'ranking.refreshData': 'Refresh Data',

    // Not Found page
    'notFound.title': '404 - Page Not Found',
    'notFound.message': 'The page you are looking for does not exist.',

    // Additional Live Trading translations
    'liveTrading.insiderBuyPriceLabel': 'Insider Buy Price',
    'liveTrading.insiderSellPriceLabel': 'Insider Sell Price',
    'liveTrading.avgInsiderBuyPriceLabel': 'Average Insider Buy Price',
    'liveTrading.aiRecommendedBuyPriceLabel': 'AI Recommended Buy Price',
    'liveTrading.currentPriceLabel': 'Current Price',
    'liveTrading.updatedLabel': 'Updated',
    'liveTrading.opportunityAfterSellLabel': 'Opportunity after insider sell',
    'liveTrading.keyFindingsLabel': 'Key Findings',
    'liveTrading.aiTargetPriceLabel': 'AI Target Price',
    'liveTrading.conservativeLabel': 'Conservative',
    'liveTrading.realisticLabel': 'Realistic',
    'liveTrading.optimisticLabel': 'Optimistic',
    'liveTrading.actionableRecommendationLabel': 'Actionable Recommendation',
    'liveTrading.catalystsIdentifiedLabel': 'Catalysts identified',
    'liveTrading.followLabel': 'Follow',
    'liveTrading.opportunisticLabel': 'Opportunistic',
    'liveTrading.comprehensiveAnalysisLabel': 'New advanced analysis results',
    'liveTrading.executiveSummaryLabel': 'Executive Summary',
    'liveTrading.keyFindingsTitle': 'Key Findings:',
    'liveTrading.aiTargetPriceTitle': 'AI Target Price:',
    'liveTrading.actionableRecommendationTitle': 'Actionable Recommendation:',
    'liveTrading.timeRangeAndCatalysts': 'Time Range and Catalysts',
    'liveTrading.defaultWatchlist': 'Default Watchlist',
    'liveTrading.defaultUserEmail': 'User Email',
    'liveTrading.performanceOptimized': 'Performance optimized data loading',
    'liveTrading.initialLoadingCount': 'Initial loading reduced count',
    'liveTrading.quickLoadingFewer': 'Initial fewer data for quick loading',
    'liveTrading.increaseStaleTime': 'Increase to 5 minutes to reduce requery frequency',
    'liveTrading.tenMinuteCache': '10 minute cache',
    'liveTrading.advancedAiAnalysisGeneration': 'Advanced AI analysis generation (replace existing stale logic)',
    'liveTrading.noTickerLoadingRelease': 'If no ticker, immediately release loading',
    'liveTrading.comprehensiveAnalysisExecution': 'Execute comprehensive analysis',
    'liveTrading.updateAnalysisResults': 'Update analysis results for that trade',
    'liveTrading.maintainBasicInsights': 'Maintain existing simple insights but replace with new ones',
    'liveTrading.provideBasicAnalysisOnFailure': 'Provide basic analysis even on failure and release loading',
    'liveTrading.buySignal': 'Buy signal',
    'liveTrading.sellSignal': 'Sell signal',
    'liveTrading.additionalMarketAnalysisNeeded': 'can be interpreted as signal but additional market analysis needed',
    'liveTrading.diversifiedInvestmentRecommended': 'Diversified portfolio investment recommended',
    'liveTrading.marketVolatility': 'Market volatility',
    'liveTrading.companyPerformance': 'Company performance',
    'liveTrading.generalMarketConditions': 'General market conditions for insider trading',
    'liveTrading.shortToMediumTerm': 'Short to medium term',
    'liveTrading.enhancedFallbackInsight': 'Enhanced fallback insight (used on failure)',
    'liveTrading.insiderLabel': 'Insider',
    'liveTrading.companySpecificAnalysis': 'Company-specific analysis',
    'liveTrading.tradeSizeAnalysis': 'Trade size analysis',
    'liveTrading.largeScale': 'Large scale',
    'liveTrading.mediumScale': 'Medium scale',
    'liveTrading.smallScale': 'Small scale',
    'liveTrading.insiderRoleImportance': 'Insider role importance',
    'liveTrading.keyExecutive': 'Key executive',
    'liveTrading.generalExecutive': 'General executive',
    'liveTrading.positiveNegativeAnalysis': 'Positive/negative analysis added',
    'liveTrading.visionProExpansion': 'Vision Pro expansion',
    'liveTrading.aiEcosystemIntegration': 'AI ecosystem integration',
    'liveTrading.indiaMarketEntry': 'India market entry',
    'liveTrading.chinaRegulatoryStrengthening': 'China regulatory strengthening',
    'liveTrading.hardwareInnovationSlowdown': 'Hardware innovation slowdown',
    'liveTrading.aiDeviceDemandSurge': 'AI device demand surge positive',
    'liveTrading.growthRateSlowdownConcerns': 'Growth rate slowdown concerns spreading',
    'liveTrading.blackwellChipLaunch': 'Blackwell chip launch',
    'liveTrading.aiSoftwareExpansion': 'AI software expansion',
    'liveTrading.automotiveAiEntry': 'Automotive AI entry',
    'liveTrading.geopoliticalRisk': 'Geopolitical risk',
    'liveTrading.valuationBurden': 'Valuation burden',
    'liveTrading.aiInfrastructureInvestmentSurge': 'AI infrastructure investment surge very positive',
    'liveTrading.overvaluationConcernsRegulatoryRisk': 'Overvaluation concerns and regulatory risk emergence',
    'liveTrading.fsdV13Launch': 'FSD v13 launch',
    'liveTrading.robotaxiCommercialization': 'Robotaxi commercialization',
    'liveTrading.energyStorageBusiness': 'Energy storage business',
    'liveTrading.evCompetitionIntensification': 'EV competition intensification',
    'liveTrading.chinaMarketShareDecline': 'China market share decline',
    'liveTrading.autonomousDrivingCommercializationExpectations': 'Autonomous driving commercialization expectations rise',
    'liveTrading.evMarketGrowthSlowdownConcerns': 'EV market growth slowdown concerns',
    'liveTrading.digitalTransformationAcceleration': 'Digital transformation acceleration',
    'liveTrading.newMarketEntry': 'New market entry',
    'liveTrading.competitiveEnvironmentDeterioration': 'Competitive environment deterioration',
    'liveTrading.costIncreasepressure': 'Cost increase pressure',
    'liveTrading.industryGrowthMomentumContinuation': 'Industry growth momentum continuation',
    'liveTrading.marketUncertaintyIncrease': 'Market uncertainty increase',
    'liveTrading.roleImportance': 'Role importance',
    'liveTrading.scaleAnalysis': 'Scale analysis',
    'liveTrading.buyExecution': 'Buy execution',
    'liveTrading.sellExecution': 'Sell execution',
    'liveTrading.millionDollars': 'Million dollars',
    'liveTrading.keyPositives': 'Key positives',
    'liveTrading.majorNegatives': 'Major negatives',
    'liveTrading.marketSentiment': 'Market sentiment',
    'liveTrading.executiveStrongConfidence': 'Executive strong confidence signal',
    'liveTrading.insiderInformationBasedInvestment': 'Insider information based investment judgment',
    'liveTrading.interpretationPossible': 'interpretation possible',
    'liveTrading.futurePerformanceConcerns': 'Future performance concerns or',
    'liveTrading.personalFundraisingOrProfitRealization': 'Personal fundraising or profit realization',
    'liveTrading.purposePossible': 'purpose possible',
    'liveTrading.sharePercentage': 'Share percentage',
    'liveTrading.companyInsights': 'Company insights',
    'liveTrading.appleInnovationEcosystemExpansion': 'Apple continuous innovation and ecosystem expansion amid',
    'liveTrading.microsoftCloudBusinessGrowthAiInvestment': 'Microsoft cloud business growth and AI investment expansion timing',
    'liveTrading.teslaEvMarketExpansionAutonomousDriving': 'Tesla EV market expansion and autonomous driving technology development process',
    'liveTrading.nvidiaAiChipDemandDataCenterExpansion': 'NVIDIA AI chip demand surge and data center expansion period',
    'liveTrading.amazonAwsGrowthLogisticsInnovation': 'Amazon AWS growth and logistics innovation acceleration timing',
    'liveTrading.companyBusinessEnvironmentChange': 'Company business environment change amid',
    'liveTrading.positiveNegativeAnalysisEnhanced': 'Positive/negative analysis included enhanced fallback insight',
    'liveTrading.iPhone16LaunchSuccess': 'iPhone 16 launch success',
    'liveTrading.aiFunctionIntegration': 'AI function integration',
    'liveTrading.serviceRevenueGrowth': 'Service revenue growth',
    'liveTrading.chinaMarketCompetitionIntensification': 'China market competition intensification',
    'liveTrading.hardwareGrowthSlowdown': 'Hardware growth slowdown',
    'liveTrading.aiEcosystemExpansionTiming': 'AI ecosystem expansion timing',
    'liveTrading.azureCloudGrowth': 'Azure cloud growth',
    'liveTrading.aiCopilotExpansion': 'AI Copilot expansion',
    'liveTrading.subscriptionServiceExpansion': 'Subscription service expansion',
    'liveTrading.cloudCompetitionIntensification': 'Cloud competition intensification',
    'liveTrading.highValuation': 'High valuation',
    'liveTrading.aiInvestmentExpansionPeriod': 'AI investment expansion period',
    'liveTrading.robotaxiDevelopment': 'Robotaxi development',
    'liveTrading.energyBusinessGrowth': 'Energy business growth',
    'liveTrading.fsdTechnologyProgress': 'FSD technology progress',
    'liveTrading.chinaProductionIssues': 'China production issues',
    'liveTrading.autonomousDrivingTechnologyTurningPoint': 'Autonomous driving technology turning point',
    'liveTrading.awsProfitabilityImprovement': 'AWS profitability improvement',
    'liveTrading.advertisingBusinessGrowth': 'Advertising business growth',
    'liveTrading.logisticsEfficiency': 'Logistics efficiency',
    'liveTrading.ecommerceGrowthSlowdown': 'E-commerce growth slowdown',
    'liveTrading.regulatoryRisk': 'Regulatory risk',
    'liveTrading.cloudProfitabilityFocusPeriod': 'Cloud profitability focus period',
    'liveTrading.corporatePerformanceImprovement': 'Corporate performance improvement',
    'liveTrading.marketExpansionOpportunity': 'Market expansion opportunity',
    'liveTrading.competitiveEnvironmentChange': 'Competitive environment change',
    'liveTrading.macroeconomicUncertainty': 'Macroeconomic uncertainty',
    'liveTrading.industryOverallChangePoint': 'Industry overall change point',
    'liveTrading.contextExecutive': 'context executive',
    'liveTrading.buyExecutionMillion': 'buy execution million',
    'liveTrading.sellExecutionMillion': 'sell execution million',
    'liveTrading.greenMajorPositives': 'Green major positives',
    'liveTrading.redMajorNegatives': 'Red major negatives',
    'liveTrading.primaryFactor': 'Primary factor',
    'liveTrading.executiveConfidenceExpression': 'Executive confidence expression interpretation possible but additional confirmation needed',
    'liveTrading.profitRealizationPurpose': 'Profit realization purpose possible but market concern signal possibility also exists',
    'liveTrading.insiderBuyAveragePriceCalculation': 'Insider buy average price calculation function',
    'liveTrading.filterBuyTradesOnly': 'Filter buy trades only for that ticker',
    'liveTrading.averagePriceCalculation': 'Average price calculation (volume weighted average)',
    'liveTrading.sophisticatedAiDataEnhancement': 'Sophisticated AI data enhancement system - memoization optimization',
    'liveTrading.similarTradeCountCalculation': 'Similar trade count calculation',
    'liveTrading.famousCompanyMoreSimilarTrades': 'Famous companies have more similar trades',
    'liveTrading.longCompanyNameUsuallyBigCompany': 'Long company names are usually big companies',
    'liveTrading.adjustmentByTradeSize': 'Adjustment by trade size',
    'liveTrading.randomAddition': 'Random addition',
    'liveTrading.maximum25Trades': 'Maximum 25 trades',
    'liveTrading.averageReturnCalculation': 'Average return calculation',
    'liveTrading.buyAveragePositive': 'Buy average +5.2%, sell -2.8%',
    'liveTrading.positionInfluence': 'Position influence',
    'liveTrading.tradeIdBasedConsistentVariation': 'Trade ID based consistent variation (generate fixed value based on hash)',
    'liveTrading.consistentVariationRange': '±3% variation (consistent)',
    'liveTrading.impactPredictionCalculation': 'Impact prediction calculation',
    'liveTrading.impactRangePercentage': 'Impact range about 80% of average return',
    'liveTrading.actualCurrentPriceAsyncLoading': 'Actual current price loaded separately asynchronously',
    'liveTrading.recommendedBuyPriceCalculatedAfterCurrentPrice': 'Recommended buy price calculated after actual current price loading',
    'liveTrading.basicInsightUntilAdvancedAnalysis': 'Basic insight (until advanced analysis)',
    'liveTrading.laterAsyncLoading': 'Later async loading',
    'liveTrading.analysisLoadingState': 'Analysis loading state',
    'liveTrading.noDependencyGenerateOnce': 'No dependency generate once',
    'liveTrading.realtimeStockUpdateFunction': 'Real-time stock update function',
    'liveTrading.excludeAlreadyLoadingSymbols': 'Exclude already loading symbols',
    'liveTrading.updateLoadingState': 'Update loading state',
    'liveTrading.updateTradeDataWithRealtimePrice': 'Update trade data with real-time price info',
    'liveTrading.aiRecommendedBuyPriceCalculation': 'AI recommended buy price calculation',
    'liveTrading.startAdvancedAnalysisAfterStockLoading': 'Start advanced analysis after stock price loading complete',
    'liveTrading.shortDelayBeforeAnalysisStart': 'Short delay before analysis start',
    'liveTrading.forceProvideAnalysisAfter10Seconds': 'Force provide fallback analysis if analysis not complete after 10 seconds',
    'liveTrading.tenSecondTimeout': '10 second timeout',
    'liveTrading.removeLoadingState': 'Remove loading state',
    'liveTrading.initializeTradesOptimized': 'Initialize trades - optimized version',
    'liveTrading.dataQualityValidation': 'Data quality validation',
    'liveTrading.dataQualityWarning': 'Data quality warning',
    'liveTrading.realtimeStockUpdate': 'Real-time stock update',
    'liveTrading.periodicStockUpdate': 'Periodic stock update (every 5 minutes)',
    'liveTrading.fiveMinutes': '5 minutes',
    'liveTrading.realtimeDataQualityValidation': 'Real-time data quality validation',
    'liveTrading.realtimeDataQualityWarning': 'Real-time data quality warning',
    'liveTrading.overallDataQualityRevalidation': 'Overall data quality revalidation',
    'liveTrading.autoRemoveAlertAfter5Seconds': 'Auto remove alert after 5 seconds',
    'liveTrading.filteringLogicUseMemoOptimization': 'Filtering logic useMemo optimization',
    'liveTrading.watchlistFiltering': 'Watchlist filtering',
    'liveTrading.infiniteScrollVirtualizationState': 'Infinite scroll and virtualization state',
    'liveTrading.loadFewerOnMobile': 'Load fewer on mobile',
    'liveTrading.infiniteScrollDetection': 'Infinite scroll detection',
    'liveTrading.tradeClickHandlersMemoization': 'Trade click handlers (memoization)',
    'liveTrading.displayTradeListVirtualized': 'Display trade list (virtualized)',
    'liveTrading.tradeTypeIconColorDefinition': 'Trade type icon and color definition',
    'liveTrading.totalFiltered': 'Total filtered',
    'liveTrading.realtimeStockLoaded': 'Real-time stock loaded',
    'liveTrading.realtimeStockUpdateButton': 'Real-time stock update button',
    'liveTrading.stockPrice': 'Stock price',
    'liveTrading.stockUpdate': 'Stock update',
    'liveTrading.realtime': 'Real-time',
    'liveTrading.connectionLost': 'Connection lost',
    'liveTrading.today': 'Today',
    'liveTrading.totalTradeVolume': 'Total trade volume',
    'liveTrading.active': 'Active',
    'liveTrading.allTrades': 'All trades',
    'liveTrading.filters': 'Filters',
    'liveTrading.buy': 'Buy',
    'liveTrading.sell': 'Sell',
    'liveTrading.stockGrant': 'Stock grant',
    'liveTrading.optionExercise': 'Option exercise',
    'liveTrading.giftDonation': 'Gift/donation',
    'liveTrading.other': 'Other',
    'liveTrading.allTradeHistory': 'All trade history',
    'liveTrading.tradesDisplayed': 'trades displayed',
    'liveTrading.noTradesMatchingFilter': 'No trades matching filter conditions',
    'liveTrading.adjustSearchConditions': 'Adjust search conditions or try different filters',
    'liveTrading.tipChangeTradeType': 'Tip: Change trade type to "All" or widen price range',
    'liveTrading.infiniteScrollLoader': 'Infinite scroll loader',
    'liveTrading.loadNewDataWhenAllLoaded': 'Load new data when all data loaded',
    'liveTrading.loadingFromServer': 'Loading from server...',
    'liveTrading.loadNewTrades': 'Load new trades',
    'liveTrading.loadNewTradesCount': 'trades at a time',
    'liveTrading.emailAlertSettingsModal': 'Email alert settings modal - Modern glassmorphism design',
    'liveTrading.glowEffect': 'Glow effect',
    'liveTrading.mainCard': 'Main card',
    'liveTrading.headerGradient': 'Header gradient',
    'liveTrading.emailInput': 'Email input',
    'liveTrading.companySelection': 'Company selection',
    'liveTrading.selectCompany': 'Select company',
    'liveTrading.pleaseSelectCompany': 'Please select a company',
    'liveTrading.alertConditionCards': 'Alert condition cards',
    'liveTrading.actionButtons': 'Action buttons',
    'liveTrading.alertSettingsSetForCompany': 'Alert settings set for company',
    'liveTrading.watchlistAddModal': 'Watchlist add modal - Success animation design',
    'liveTrading.successGlowEffect': 'Success glow effect',
    'liveTrading.successHeaderLine': 'Success header line',
    'liveTrading.successCheckAnimation': 'Success check animation',
    'liveTrading.companyInfoCard': 'Company info card',
    'liveTrading.companyLogoPlaceholder': 'Company logo placeholder',
    'liveTrading.successMessageCard': 'Success message card',
    'liveTrading.nowYouCanView': 'Now you can view',
    'liveTrading.myWatchlistTab': 'My Watchlist tab',
    'liveTrading.insiderTradingInfoSeparately': 'insider trading info separately',
    'liveTrading.additionalFeatureHint': 'Additional feature hint',
    'liveTrading.close': 'Close',
    'liveTrading.tradeDetailInfoModal': 'Trade detail info modal',
    'liveTrading.dataQualityDetailsModal': 'Data quality details modal',
    'liveTrading.summary': 'Summary',
    'liveTrading.issueList': 'Issue list',
    'liveTrading.discoveredIssues': 'Discovered issues',
    'liveTrading.affectedTrades': 'Affected trades',
    'liveTrading.recommendations': 'Recommendations',

    // Trade Detail Modal
    'tradeDetail.shareCount': 'Share Count',
    'tradeDetail.insiderInfo': 'Insider Information',
    'tradeDetail.position': 'Position',
    'tradeDetail.reportDate': 'Report Date',
    'tradeDetail.priceAnalysis': 'Price Analysis & Investment Insights',
    'tradeDetail.keyMetrics': 'Key Metrics',
    'tradeDetail.insiderTradePrice': 'Insider Trade Price',
    'tradeDetail.insiderAvgTradePrice': 'Insider Average Trade Price',
    'tradeDetail.integratedAiAnalysis': 'Integrated AI Analysis Results',
    'tradeDetail.basicInfo': 'Basic Information',
    'tradeDetail.priceAnalysisDashboard': 'Price Analysis Dashboard',
    'tradeDetail.marketOpeningHours': 'Market opening hours check (US Eastern Time)',
    'tradeDetail.weekendExcluded': 'Weekend excluded (Mon-Fri)',
    'tradeDetail.marketHours': 'Market hours: 9:30 AM - 4:00 PM ET',
    'tradeDetail.insiderPulseWatermark': 'InsiderPulse watermark - fixed to modal center',

    // Dashboard
    'dashboard.loadMoreTradesError': 'Failed to load more trades. Please try again.',
  },
  ko: {
    // Navigation
    'nav.dashboard': '대시보드',
    'nav.livetrading': '실시간 거래',
    'nav.analytics': '분석',
    'nav.alerts': '알림',
    'nav.search': '검색',
    'nav.ranking': '추천주식',
    'nav.settings': '설정',
    
    // Dashboard
    'dashboard.title': '인사이더트랙 프로',
    'dashboard.subtitle': 'AI 기반 내부자 거래 모니터',
    'dashboard.lastUpdated': '최종 업데이트',
    'dashboard.stats.todayTrades': '오늘의 거래',
    'dashboard.stats.totalVolume': '총 거래량',
    'dashboard.recentActivity': '최근 활동',
    'dashboard.marketCoverage': '시장 커버리지',
    'dashboard.topMoversToday': '오늘의 급등주',
    
    // Trades
    'trades.loadingStats': '거래 통계를 불러오는 중...',
    'trades.failedStats': '거래 통계를 불러오지 못했습니다. 페이지를 새로고침 해주세요.',
    'trades.recentTrades': '최근 내부자 거래',
    'trades.loadingTrades': '거래 정보를 불러오는 중...',
    'trades.viewDetails': '자세히 보기',
    'trades.loadMore': '더 많은 거래 보기',
    'trades.noTrades': '거래 정보가 없습니다',
    'trades.company': '회사',
    'trades.shares': '주식 수',
    'trades.price': '가격',
    'trades.total': '총 가치',
    'trades.signal': '신호',
    'trades.significance': '중요도',
    'trades.filed': '신고일',
    
    // Settings
    'settings.title': '설정',
    'settings.language': '언어',
    'settings.theme': '테마',
    'settings.notifications': '알림',
    'settings.language.english': '영어',
    'settings.language.korean': '한국어',
    'settings.language.japanese': '일본어',
    'settings.language.chinese': '중국어',
    'settings.theme.light': '라이트',
    'settings.theme.dark': '다크',
    'settings.theme.system': '시스템',
    'settings.description': '애플리케이션 환경설정과 설정을 관리합니다.',
    'settings.themeDescription': '선호하는 테마를 선택하세요',
    'settings.notificationsFuture': '알림 설정은 향후 업데이트에서 제공됩니다.',
    
    // WebSocket Status
    'websocket.connected': '실시간 피드에 연결됨',
    'websocket.disconnected': '실시간 피드 연결 끊김',
    'websocket.connecting': '실시간 피드에 연결 중...',
    
    // General
    'general.loading': '로딩 중...',
    'general.error': '오류',
    'general.success': '성공',
    'general.refresh': '새로고침',
    'general.save': '저장',
    'general.cancel': '취소',
    'general.delete': '삭제',
    
    // Page specific
    'page.dashboard.subtitle': '실시간 내부자 거래 모니터링 및 시장 인텔리전스',
    'page.livetrading.title': '실시간 거래',
    'page.livetrading.subtitle': 'AI 기반 분석과 함께하는 실시간 내부자 거래 활동',
    'page.search.placeholder': '회사명, 티커, 거래자, 직책 검색...',
    'page.alerts.title': '스마트 알림',
    'page.alerts.subtitle': '내부자 거래 활동에 대한 지능형 알림 설정',
    'page.analytics.title': '시장 분석',
    'page.analytics.subtitle': '내부자 거래 패턴의 포괄적 분석',
    
    // WebSocket and Connection
    'connection.liveFeedActive': '실시간 데이터 피드 활성화 - 실시간 SEC 신고 모니터링',
    'connection.connectionLost': '연결이 끊어졌습니다 - 재연결을 시도하는 중...',
    'connection.liveFeed': '실시간 피드',
    'connection.disconnected': '연결 끊김',
    
    // Statistics and Data
    'stats.todayTrades': '오늘의 거래',
    'stats.totalVolume': '총 거래량',
    'stats.tradingSummary': '거래 요약',
    'stats.failedLoad': '거래 통계를 불러오지 못했습니다. 페이지를 새로고침 해주세요.',
    'stats.fromLastWeek': '지난주 대비',
    
    // Filters and Search
    'filter.allTypes': '모든 유형',
    'filter.buyOrders': '매수 주문',
    'filter.sellOrders': '매도 주문',
    'filter.allSignals': '모든 신호',
    'filter.buySignal': '매수 신호',
    'filter.sellSignal': '매도 신호',
    'filter.holdSignal': '보유 신호',
    'filter.buyOnly': '매수만',
    'filter.sellOnly': '매도만',
    
    // Placeholders
    'placeholder.searchCompany': '회사 검색...',
    'placeholder.searchTrader': '거래자 검색...',
    'placeholder.noLimit': '제한 없음',
    'placeholder.preferredLanguage': '선호하는 언어를 선택하세요',
    
    // Alert types
    'alerts.type.volume': '거래량',
    'alerts.type.company': '회사명',
    'alerts.type.trader': '거래자 직책',
    
    // Search page
    'search.title': '검색 및 필터',
    'search.subtitle': '고급 기준으로 내부자 거래 데이터를 검색하고 필터링',
    'search.filters': '필터',
    'search.clear': '지우기',
    'search.tradeType': '거래 유형',
    'search.dateRange': '날짜 범위',
    'search.sortBy': '정렬 기준',
    'search.dateRange.all': '전체 기간',
    'search.dateRange.7d': '최근 7일',
    'search.dateRange.30d': '최근 30일',
    'search.dateRange.90d': '최근 90일',
    'search.sort.recent': '최신순',
    'search.sort.value': '금액순',
    'search.sort.company': '회사명',
    'search.results': '결과',
    'search.buyTrades': '매수 거래',
    'search.sellTrades': '매도 거래',
    'search.totalVolume': '총 거래량',
    'search.companies': '회사',
    'search.traders': '거래자',
    'search.totalFound': '총 거래 건수',
    'search.combinedValue': '통합 가치',
    'search.uniqueEntities': '고유 기업',
    'search.uniqueInsiders': '고유 내부자',
    'search.searchResults': '검색 결과',
    'search.noTrades': '거래가 없습니다',
    'search.placeholder.minValue': '1000000',
    'search.value': '최소 값',
    
    // Alerts page
    'alerts.title': '스마트 알림',
    'alerts.subtitle': '내부자 거래 활동에 대한 지능형 알림 설정',
    'alerts.active': '활성 알림',
    'alerts.createNew': '새 알림 만들기',
    'alerts.alertName': '알림 이름',
    'alerts.alertType': '알림 유형',
    'alerts.condition': '조건',
    'alerts.value': '값',
    'alerts.paused': '일시정지',
    'alerts.noAlerts': '아직 설정된 알림이 없습니다',
    'alerts.createFirst': '아래에서 첫 번째 알림을 생성하세요',
    'alerts.noMatches': '최근 일치하는 항목이 없습니다',
    'alerts.setupMatches': '일치하는 항목을 보려면 알림을 설정하세요',
    'alerts.condition.greaterThan': '초과',
    'alerts.condition.lessThan': '미만',
    'alerts.condition.equals': '같음',
    'alerts.condition.contains': '포함',
    'alerts.placeholder.name': '예: 대형 애플 거래',
    'alerts.recentMatches': '최근 일치',
    
    // Live Trading page
    'liveTrading.filtersAndSearch': '필터 및 검색',
    'liveTrading.tradeType': '거래 유형',
    'liveTrading.aiSignal': 'AI 신호',
    'liveTrading.companyTicker': '회사/티커',
    'liveTrading.traderName': '거래자 이름',
    'liveTrading.minValue': '최소 값 ($)',
    'liveTrading.maxValue': '최대 값 ($)',
    'liveTrading.liveFeed': '최근 내부자 거래 (1개월치만 표시)',
    'liveTrading.tradesShown': '거래 표시됨',
    'liveTrading.noTrades': '거래가 없습니다',
    'liveTrading.adjustFilters': '필터를 조정해 보세요',
    'liveTrading.insider': '내부자',
    'liveTrading.tradeDetails': '거래 세부정보',
    'liveTrading.totalValue': '총 가치',
    'liveTrading.score': '점수:',
    'liveTrading.loadMore': '더 많은 거래 불러오기',
    'liveTrading.activeNow': '현재 활성',
    'liveTrading.alertsSet': '알림 설정',
    'liveTrading.pageTitle': '모든 거래 표시 및 검색',
    'liveTrading.pageTitleMobile': '거래 검색',
    'liveTrading.pageSubtitle': '모든 내부자 거래 데이터를 검색하고 필터링할 수 있습니다',
    'liveTrading.totalTrades': '총',
    'liveTrading.filtered': '필터링',
    'liveTrading.realtimeStock': '실시간 주가',
    'liveTrading.loaded': '로드됨',
    'liveTrading.loading': '로딩 중',
    'liveTrading.dataQuality': '데이터 품질',
    'liveTrading.issues': '개 이슈',
    'liveTrading.loadingTrades': '거래 데이터를 불러오는 중...',
    'liveTrading.alert': '알림',
    'liveTrading.watchlist': '워치리스트',
    'liveTrading.added': '추가됨',
    'liveTrading.watch': '워치',
    'liveTrading.advancedAiAnalysis': '고급 AI 분석',
    'liveTrading.confidenceLevel': '신뢰도',
    'liveTrading.advancedAnalyzing': '고급 AI 분석 중...',
    'liveTrading.realtimePriceInfo': '실시간 가격 정보',
    'liveTrading.insiderTradePrice': '내부자 거래가',
    'liveTrading.expectedImpact': '예상 영향',
    'liveTrading.similarTrades': '유사 거래',
    'liveTrading.count': '건',
    'liveTrading.pieces': '개',
    'liveTrading.analysisInProgress': '뉴스, 재무 데이터, 내부자 패턴을 종합 분석하고 있습니다',
    'liveTrading.basicAnalysis': '기본 분석',
    'liveTrading.loadingTradeData': '거래 데이터 로딩 중...',
    'liveTrading.fetchingLatestInsider': '최신 내부자 거래 정보를 불러오고 있습니다',
    'liveTrading.avgLoadingTime': '💡 평균 로딩 시간: 3-5초',
    'liveTrading.remaining': '개 남음',
    'liveTrading.myWatchlist': '내 워치리스트',
    'liveTrading.addToWatchlist': '워치리스트 추가',
    'liveTrading.emailAlerts': '이메일 알림',
    'liveTrading.smartAlerts': '스마트 알림',
    'liveTrading.watchlistAdded': '워치리스트 추가됨',
    'liveTrading.realtimeAlertsAvailable': '실시간 알림 설정도 가능합니다',
    'liveTrading.getRealtimeAlerts': '실시간 거래 알림을 받아보세요',
    'liveTrading.alertEmail': '알림 받을 이메일',
    'liveTrading.alertConditions': '알림 조건',
    'liveTrading.successfullyAdded': '성공적으로 추가되었습니다!',
    'liveTrading.additionComplete': '추가 완료!',
    'liveTrading.canViewSeparately': '의 내부자 거래 정보만 따로 볼 수 있습니다',
    'liveTrading.viewWatchlist': '워치리스트 보기',
    'liveTrading.whenInsiderTrade': '내부자 거래 발생 시',
    'liveTrading.whenPriceChange': '주가 급등락 시',
    'liveTrading.whenVolumeSpike': '거래량 급증 시',
    'liveTrading.largeTrades': '대량 거래 ($10M+)',
    'liveTrading.whenRecommendedPrice': '추천 매수가격 도달 시',
    'liveTrading.dataQualityReport': '데이터 품질 리포트',
    'liveTrading.validTrades': '유효한 거래',
    
    // Trade Card
    'tradeCard.filed': '신고됨',
    'tradeCard.shares': '주식수',
    'tradeCard.avgPrice': '평균 가격',
    'tradeCard.totalValue': '총 가치',
    'tradeCard.ownership': '소유권',
    'tradeCard.details': '세부정보',
    
    // Trade List
    'tradeList.recentTrades': '최근 내부자 거래',
    'tradeList.searchCompanies': '회사 검색...',
    'tradeList.sort': '정렬:',
    'tradeList.date': '날짜',
    'tradeList.value': '가치',
    'tradeList.noTradesFound': '조건에 맞는 거래가 없습니다.',
    'tradeList.loading': '로딩 중...',
    'tradeList.loadMore': '더 많은 거래 불러오기',
    'tradeList.noMatches': '조건에 맞는 거래가 없습니다.',
    'tradeList.searchPlaceholder': '회사 검색...',
    
    // Dashboard Stats
    'dashboardStats.todayTrades': '오늘의 거래',
    'dashboardStats.totalVolume': '총 거래량',
    'dashboardStats.fromLastWeek': '지난주 대비',
    'dashboardStats.recentActivity': '최근 활동',
    'dashboardStats.monitoring': '모든 주요 거래소에서 내부자 거래 모니터링',
    'dashboardStats.marketCoverage': '시장 커버리지',
    'dashboardStats.realTimeAnalysis': '실시간 SEC 신고 분석 및 거래 분류',
    'dashboardStats.topMovers': '오늘의 최고 상승주',
    
    // Analytics page
    'analytics.subtitle': '포괄적인 내부자 거래 시장 분석 및 인사이트',
    'analytics.totalTrades': '총 거래',
    'analytics.transactionsRecorded': '기록된 내부자 거래',
    'analytics.totalVolume': '총 거래량',
    'analytics.combinedValue': '통합 거래 가치',
    'analytics.avgTradeSize': '평균 거래 규모',
    'analytics.averageValue': '평균 거래 가치',
    'analytics.companies': '회사',
    'analytics.uniqueTracked': '추적된 고유 회사',
    'analytics.tradeDistribution': '거래 유형 분포',
    'analytics.monthlyActivity': '월별 거래 활동',
    'analytics.topCompanies': '거래량 상위 회사',
    'analytics.trades': '거래',
    'analytics.combinedTransactionValue': '통합 거래 가치',
    'analytics.averageTransactionValue': '평균 거래 가치',
    'analytics.uniqueCompaniesTracked': '추적된 고유 회사',
    'analytics.tradeTypeDistribution': '거래 유형 분포',
    'analytics.monthlyTradingActivity': '월별 거래 활동',
    'analytics.topCompaniesByVolume': '거래량 상위 회사',
    'analytics.buys': '매수',
    'analytics.sells': '매도',
    
    // Trade Detail page
    'tradeDetail.notFound': '거래를 찾을 수 없음',
    'tradeDetail.notFoundMessage': '요청한 거래를 찾을 수 없습니다.',
    'tradeDetail.backToDashboard': '대시보드로 돌아가기',
    'tradeDetail.back': '뒤로',
    'tradeDetail.title': '거래 세부정보',
    'tradeDetail.companyInfo': '회사 정보',
    'tradeDetail.company': '회사',
    'tradeDetail.tickerSymbol': '티커 심볼',
    'tradeDetail.tradeType': '거래 유형',
    'tradeDetail.traderInfo': '거래자 정보',
    'tradeDetail.name': '이름',
    'tradeDetail.titlePosition': '직책/지위',
    'tradeDetail.ownership': '소유권',
    'tradeDetail.transactionDetails': '거래 세부정보',
    'tradeDetail.sharesTraded': '거래된 주식수',
    'tradeDetail.pricePerShare': '주당 가격',
    'tradeDetail.totalValue': '총 거래 가치',
    'tradeDetail.filingDate': '신고 날짜',
    'tradeDetail.currentPrice': '현재 주가',
    'tradeDetail.volume': '거래량',
    'tradeDetail.lastUpdated': '최종 업데이트',
    'tradeDetail.analysis': '상세 분석',
    'tradeDetail.priceComparison': '가격 비교',
    'tradeDetail.tradePrice': '거래 가격:',
    'tradeDetail.currentPriceLabel': '현재 가격:',
    'tradeDetail.perShareComparison': '주당 비교',
    'tradeDetail.secFiling': 'SEC 신고 #',
    'tradeDetail.totalTransactionValue': '총 거래 가치',
    'tradeDetail.currentStockPrice': '현재 주가',
    'tradeDetail.detailedAnalysis': '상세 분석',
    'tradeDetail.actualTradePrice': '실제 거래 가격',
    'tradeDetail.insiderAvgPrice': '내부자 평균거래가',
    'tradeDetail.last30DaysAvg': '최근 30일 평균',
    'tradeDetail.sameTicker': '동일 티커 평균',
    'tradeDetail.currentMarketPrice': '현재 시장가',
    'tradeDetail.realtimeEstimate': '실시간 추정',
    'tradeDetail.marketClosed': '휴장 (최근가)',
    'tradeDetail.realtimePrice': '실시간 가격',
    'tradeDetail.lastClosePrice': '마지막 종가 (휴장 중)',
    'tradeDetail.aiAnalysisResults': 'AI 분석결과',
    'tradeDetail.tradingPatternAnalysis': '거래 패턴 분석',
    'tradeDetail.investmentStrategy': '투자 전략',
    'tradeDetail.additionalInsights': '추가 인사이트',
    
    // Price Comparison Chart
    'priceChart.title': '가격 비교 차트',
    'priceChart.tradePrice': '거래 가격',
    'priceChart.currentPrice': '현재 가격',
    'priceChart.today': '오늘',
    'priceChart.insiderTrade': '내부자 거래',
    'priceChart.movement': '거래 이후 가격 변동',
    'priceChart.increased': '가격 상승',
    'priceChart.decreased': '가격 하락',
    'priceChart.tradePriceLabel': '거래 가격:',
    'priceChart.currentLabel': '현재:',
    
    // Ranking page
    'ranking.title': '추천매수 순위',
    'ranking.subtitle': '내부자 거래 패턴을 기반으로 한 AI 주식 추천',
    'ranking.topStocks': '추천 주식 TOP 10',
    'ranking.recommendation': '추천',
    'ranking.buyPotential': '매수 잠재력',
    'ranking.marketCap': '시가총액',
    'ranking.volume': '거래량',
    'ranking.priceChange': '가격 변동',
    'ranking.lastPrice': '현재 가격',
    'ranking.strongBuy': '적극매수',
    'ranking.buy': '매수',
    'ranking.hold': '보유',
    'ranking.analysis': '분석',
    'ranking.insiderActivity': '내부자 활동',
    'ranking.tradesLast30Days': '최근 30일 거래',
    'ranking.avgTradeValue': '평균 거래 가치',
    'ranking.netBuying': '순매수',
    'ranking.loading': '주식 순위를 불러오는 중...',
    'ranking.noData': '순위 데이터가 없습니다',
    'ranking.refreshData': '데이터 새로고침',

    // Not Found page
    'notFound.title': '404 - 페이지를 찾을 수 없습니다',
    'notFound.message': '요청하신 페이지가 존재하지 않습니다.',
  },
  ja: {
    // Navigation
    'nav.dashboard': 'ダッシュボード',
    'nav.livetrading': 'ライブトレーディング',
    'nav.analytics': '分析',
    'nav.alerts': 'アラート',
    'nav.search': '検索',
    'nav.ranking': 'トップ株',
    'nav.settings': '設定',
    
    // Dashboard
    'dashboard.title': 'インサイダートラック プロ',
    'dashboard.subtitle': 'AI搭載インサイダー取引モニター',
    'dashboard.lastUpdated': '最終更新',
    'dashboard.stats.todayTrades': '今日の取引',
    'dashboard.stats.totalVolume': '総取引量',
    'dashboard.recentActivity': '最近の活動',
    'dashboard.marketCoverage': '市場カバレッジ',
    'dashboard.topMoversToday': '今日の値上がり株',
    
    // Trades
    'trades.loadingStats': '取引統計を読み込み中...',
    'trades.failedStats': '取引統計の読み込みに失敗しました。ページを更新してください。',
    'trades.recentTrades': '最近のインサイダー取引',
    'trades.loadingTrades': '取引を読み込み中...',
    'trades.viewDetails': '詳細を見る',
    'trades.loadMore': 'さらに取引を読み込む',
    'trades.noTrades': '取引がありません',
    'trades.company': '会社',
    'trades.shares': '株式数',
    'trades.price': '価格',
    'trades.total': '総価値',
    'trades.signal': 'シグナル',
    'trades.significance': '重要度',
    'trades.filed': '提出日',
    
    // Settings
    'settings.title': '設定',
    'settings.language': '言語',
    'settings.theme': 'テーマ',
    'settings.notifications': '通知',
    'settings.language.english': '英語',
    'settings.language.korean': '韓国語',
    'settings.language.japanese': '日本語',
    'settings.language.chinese': '中国語',
    'settings.theme.light': 'ライト',
    'settings.theme.dark': 'ダーク',
    'settings.theme.system': 'システム',
    'settings.description': 'アプリケーションの設定と環境設定を管理します。',
    'settings.themeDescription': '好みのテーマを選択してください',
    'settings.notificationsFuture': '通知設定は今後のアップデートで利用可能になります。',
    
    // WebSocket Status
    'websocket.connected': 'ライブフィードに接続済み',
    'websocket.disconnected': 'ライブフィードから切断',
    'websocket.connecting': 'ライブフィードに接続中...',
    
    // General
    'general.loading': '読み込み中...',
    'general.error': 'エラー',
    'general.success': '成功',
    'general.refresh': '更新',
    'general.save': '保存',
    'general.cancel': 'キャンセル',
    'general.delete': '削除',
    
    // Page specific
    'page.dashboard.subtitle': 'リアルタイムインサイダー取引監視と市場インテリジェンス',
    'page.livetrading.title': 'ライブトレーディング',
    'page.livetrading.subtitle': 'AI搭載分析によるリアルタイムインサイダー取引活動',
    'page.search.placeholder': '企業、ティッカー、トレーダー、役職を検索...',
    'page.alerts.title': 'スマートアラート',
    'page.alerts.subtitle': 'インサイダー取引活動のインテリジェントアラート設定',
    'page.analytics.title': '市場分析',
    'page.analytics.subtitle': 'インサイダー取引パターンの包括的分析',
    
    // WebSocket and Connection
    'connection.liveFeedActive': 'ライブデータフィード有効 - リアルタイムSEC申告監視',
    'connection.connectionLost': '接続が失われました - 再接続を試行中...',
    'connection.liveFeed': 'ライブフィード',
    'connection.disconnected': '切断済み',
    
    // Statistics and Data
    'stats.todayTrades': '今日の取引',
    'stats.totalVolume': '総取引量',
    'stats.tradingSummary': '取引サマリー',
    'stats.failedLoad': '取引統計の読み込みに失敗しました。ページを更新してください。',
    'stats.fromLastWeek': '先週比',
    
    // Filters and Search
    'filter.allTypes': 'すべてのタイプ',
    'filter.buyOrders': '買い注文',
    'filter.sellOrders': '売り注文',
    'filter.allSignals': 'すべてのシグナル',
    'filter.buySignal': '買いシグナル',
    'filter.sellSignal': '売りシグナル',
    'filter.holdSignal': 'ホールドシグナル',
    'filter.buyOnly': '買いのみ',
    'filter.sellOnly': '売りのみ',
    
    // Placeholders
    'placeholder.searchCompany': '企業を検索...',
    'placeholder.searchTrader': 'トレーダーを検索...',
    'placeholder.noLimit': '制限なし',
    'placeholder.preferredLanguage': '好みの言語を選択してください',
    
    // Alert types
    'alerts.type.volume': '取引量',
    'alerts.type.company': '会社名',
    'alerts.type.trader': 'トレーダー役職',
    
    // Search page
    'search.title': '検索とフィルター',
    'search.subtitle': '高度な条件でインサイダー取引データを検索・フィルタリング',
    'search.filters': 'フィルター',
    'search.clear': 'クリア',
    'search.tradeType': '取引タイプ',
    'search.dateRange': '日付範囲',
    'search.sortBy': '並び順',
    'search.dateRange.all': '全期間',
    'search.dateRange.7d': '過去7日',
    'search.dateRange.30d': '過去30日',
    'search.dateRange.90d': '過去90日',
    'search.sort.recent': '最新順',
    'search.sort.value': '金額順',
    'search.sort.company': '会社名',
    'search.results': '結果',
    'search.buyTrades': '買い取引',
    'search.sellTrades': '売り取引',
    'search.totalVolume': '総取引量',
    'search.companies': '企業',
    'search.traders': 'トレーダー',
    'search.totalFound': '総取引数',
    'search.combinedValue': '合計価値',
    'search.uniqueEntities': 'ユニーク企業',
    'search.uniqueInsiders': 'ユニークインサイダー',
    'search.searchResults': '検索結果',
    'search.noTrades': '取引が見つかりません',
    'search.placeholder.minValue': '1000000',
    'search.value': '最小値',
    
    // Alerts page
    'alerts.title': 'スマートアラート',
    'alerts.subtitle': 'インサイダー取引活動のインテリジェントアラート設定',
    'alerts.active': 'アクティブアラート',
    'alerts.createNew': '新しいアラートを作成',
    'alerts.alertName': 'アラート名',
    'alerts.alertType': 'アラートタイプ',
    'alerts.condition': '条件',
    'alerts.value': '値',
    'alerts.paused': '一時停止',
    'alerts.noAlerts': 'アラートが設定されていません',
    'alerts.createFirst': '下で最初のアラートを作成してください',
    'alerts.noMatches': '最近の一致がありません',
    'alerts.setupMatches': 'アラートを設定して一致を確認してください',
    'alerts.condition.greaterThan': '以上',
    'alerts.condition.lessThan': '未満',
    'alerts.condition.equals': '等しい',
    'alerts.condition.contains': '含む',
    'alerts.placeholder.name': '例：大型アップル取引',
    'alerts.recentMatches': '最近の一致',
    
    // Live Trading page
    'liveTrading.filtersAndSearch': 'フィルターと検索',
    'liveTrading.tradeType': '取引タイプ',
    'liveTrading.aiSignal': 'AIシグナル',
    'liveTrading.companyTicker': '企業/ティッカー',
    'liveTrading.traderName': 'トレーダー名',
    'liveTrading.minValue': '最小値 ($)',
    'liveTrading.maxValue': '最大値 ($)',
    'liveTrading.liveFeed': 'ライブ取引フィード',
    'liveTrading.tradesShown': '取引表示中',
    'liveTrading.noTrades': '取引が見つかりません',
    'liveTrading.adjustFilters': 'フィルターを調整してください',
    'liveTrading.insider': 'インサイダー',
    'liveTrading.tradeDetails': '取引詳細',
    'liveTrading.totalValue': '総価値',
    'liveTrading.score': 'スコア:',
    'liveTrading.loadMore': 'さらに取引を読み込む',
    'liveTrading.activeNow': '現在アクティブ',
    'liveTrading.alertsSet': 'アラート設定',
    'liveTrading.pageTitle': 'すべての取引表示と検索',
    'liveTrading.pageTitleMobile': '取引検索',
    'liveTrading.pageSubtitle': 'すべてのインサイダー取引データを検索・フィルタリング',
    'liveTrading.totalTrades': '総',
    'liveTrading.filtered': 'フィルタリング',
    'liveTrading.realtimeStock': 'リアルタイム株価',
    'liveTrading.loaded': 'ロード済み',
    'liveTrading.loading': 'ロード中',
    'liveTrading.dataQuality': 'データ品質',
    'liveTrading.issues': '個の問題',
    'liveTrading.loadingTrades': '取引データをロード中...',
    'liveTrading.alert': 'アラート',
    'liveTrading.watchlist': 'ウォッチリスト',
    'liveTrading.added': '追加済み',
    'liveTrading.watch': 'ウォッチ',
    'liveTrading.advancedAiAnalysis': '高度AI分析',
    'liveTrading.confidenceLevel': '信頼度',
    'liveTrading.advancedAnalyzing': '高度AI分析中...',
    'liveTrading.realtimePriceInfo': 'リアルタイム価格情報',
    'liveTrading.insiderTradePrice': 'インサイダー取引価格',
    'liveTrading.expectedImpact': '予想影響',
    'liveTrading.similarTrades': '類似取引',
    'liveTrading.count': '件',
    'liveTrading.pieces': '個',
    'liveTrading.analysisInProgress': 'ニュース、財務データ、インサイダーパターンを総合的に分析中',
    'liveTrading.basicAnalysis': '基本分析',
    'liveTrading.loadingTradeData': '取引データをロード中...',
    'liveTrading.fetchingLatestInsider': '最新のインサイダー取引情報を取得中',
    'liveTrading.avgLoadingTime': '💡 平均ロード時間: 3-5秒',
    'liveTrading.remaining': '件残り',
    'liveTrading.myWatchlist': '私のウォッチリスト',
    'liveTrading.addToWatchlist': 'ウォッチリストに追加',
    'liveTrading.emailAlerts': 'メールアラート',
    'liveTrading.smartAlerts': 'スマートアラート',
    'liveTrading.watchlistAdded': 'ウォッチリストに追加済み',
    'liveTrading.realtimeAlertsAvailable': 'リアルタイムアラート設定も可能です',
    'liveTrading.getRealtimeAlerts': 'リアルタイム取引アラートを受信',
    'liveTrading.alertEmail': 'アラート受信メール',
    'liveTrading.alertConditions': 'アラート条件',
    'liveTrading.successfullyAdded': '正常に追加されました!',
    'liveTrading.additionComplete': '追加完了!',
    'liveTrading.canViewSeparately': 'のインサイダー取引情報を別々に表示できます',
    'liveTrading.viewWatchlist': 'ウォッチリストを表示',
    'liveTrading.whenInsiderTrade': 'インサイダー取引発生時',
    'liveTrading.whenPriceChange': '株価急変時',
    'liveTrading.whenVolumeSpike': '取引量急増時',
    'liveTrading.largeTrades': '大量取引 ($10M+)',
    'liveTrading.whenRecommendedPrice': '推奨買い価格到達時',
    'liveTrading.dataQualityReport': 'データ品質レポート',
    'liveTrading.validTrades': '有効な取引',
    
    // Trade Card
    'tradeCard.filed': '提出済み',
    'tradeCard.shares': '株式数',
    'tradeCard.avgPrice': '平均価格',
    'tradeCard.totalValue': '総価値',
    'tradeCard.ownership': '所有権',
    'tradeCard.details': '詳細',
    
    // Trade List
    'tradeList.recentTrades': '最近のインサイダー取引',
    'tradeList.searchCompanies': '企業を検索...',
    'tradeList.sort': 'ソート:',
    'tradeList.date': '日付',
    'tradeList.value': '価値',
    'tradeList.noTradesFound': '条件に一致する取引が見つかりません。',
    'tradeList.loading': '読み込み中...',
    'tradeList.loadMore': 'さらに取引を読み込む',
    'tradeList.noMatches': '条件に一致する取引が見つかりません。',
    'tradeList.searchPlaceholder': '企業を検索...',
    
    // Dashboard Stats
    'dashboardStats.todayTrades': '今日の取引',
    'dashboardStats.totalVolume': '総取引量',
    'dashboardStats.fromLastWeek': '先週比',
    'dashboardStats.recentActivity': '最近の活動',
    'dashboardStats.monitoring': 'すべての主要取引所でインサイダー取引を監視',
    'dashboardStats.marketCoverage': '市場カバレッジ',
    'dashboardStats.realTimeAnalysis': 'リアルタイムSEC申告分析と取引分類',
    'dashboardStats.topMovers': '今日のトップムーバー',
    
    // Analytics page
    'analytics.subtitle': '包括的なインサイダー取引市場分析とインサイト',
    'analytics.totalTrades': '総取引数',
    'analytics.transactionsRecorded': '記録されたインサイダー取引',
    'analytics.totalVolume': '総取引量',
    'analytics.combinedValue': '合計取引価値',
    'analytics.avgTradeSize': '平均取引規模',
    'analytics.averageValue': '平均取引価値',
    'analytics.companies': '企業',
    'analytics.uniqueTracked': '追跡されたユニーク企業',
    'analytics.tradeDistribution': '取引タイプ分布',
    'analytics.monthlyActivity': '月次取引活動',
    'analytics.topCompanies': '取引量上位企業',
    'analytics.trades': '取引',
    'analytics.combinedTransactionValue': '合計取引価値',
    'analytics.averageTransactionValue': '平均取引価値',
    'analytics.uniqueCompaniesTracked': '追跡されたユニーク企業',
    'analytics.tradeTypeDistribution': '取引タイプ分布',
    'analytics.monthlyTradingActivity': '月次取引活動',
    'analytics.topCompaniesByVolume': '取引量上位企業',
    'analytics.buys': '買い',
    'analytics.sells': '売り',
    
    // Trade Detail page
    'tradeDetail.notFound': '取引が見つかりません',
    'tradeDetail.notFoundMessage': '要求された取引が見つかりませんでした。',
    'tradeDetail.backToDashboard': 'ダッシュボードに戻る',
    'tradeDetail.back': '戻る',
    'tradeDetail.title': '取引詳細',
    'tradeDetail.companyInfo': '企業情報',
    'tradeDetail.company': '企業',
    'tradeDetail.tickerSymbol': 'ティッカーシンボル',
    'tradeDetail.tradeType': '取引タイプ',
    'tradeDetail.traderInfo': 'トレーダー情報',
    'tradeDetail.name': '名前',
    'tradeDetail.titlePosition': '役職/地位',
    'tradeDetail.ownership': '所有権',
    'tradeDetail.transactionDetails': '取引詳細',
    'tradeDetail.sharesTraded': '取引株式数',
    'tradeDetail.pricePerShare': '1株当たり価格',
    'tradeDetail.totalValue': '総取引価値',
    'tradeDetail.filingDate': '申告日',
    'tradeDetail.currentPrice': '現在の株価',
    'tradeDetail.volume': '取引量',
    'tradeDetail.lastUpdated': '最終更新',
    'tradeDetail.analysis': '詳細分析',
    'tradeDetail.priceComparison': '価格比較',
    'tradeDetail.tradePrice': '取引価格:',
    'tradeDetail.currentPriceLabel': '現在価格:',
    'tradeDetail.perShareComparison': '1株当たり比較',
    'tradeDetail.secFiling': 'SEC申告 #',
    'tradeDetail.totalTransactionValue': '総取引価値',
    'tradeDetail.currentStockPrice': '現在の株価',
    'tradeDetail.detailedAnalysis': '詳細分析',
    'tradeDetail.actualTradePrice': '実際の取引価格',
    'tradeDetail.insiderAvgPrice': 'インサイダー平均取引価格',
    'tradeDetail.last30DaysAvg': '過去30日平均',
    'tradeDetail.sameTicker': '同一ティッカー平均',
    'tradeDetail.currentMarketPrice': '現在の市場価格',
    'tradeDetail.realtimeEstimate': 'リアルタイム推定',
    'tradeDetail.marketClosed': '休場（最終価格）',
    'tradeDetail.realtimePrice': 'リアルタイム価格',
    'tradeDetail.lastClosePrice': '最終終値（休場中）',
    'tradeDetail.aiAnalysisResults': 'AI分析結果',
    'tradeDetail.tradingPatternAnalysis': '取引パターン分析',
    'tradeDetail.investmentStrategy': '投資戦略',
    'tradeDetail.additionalInsights': '追加インサイト',
    
    // Price Comparison Chart
    'priceChart.title': '価格比較チャート',
    'priceChart.tradePrice': '取引価格',
    'priceChart.currentPrice': '現在価格',
    'priceChart.today': '今日',
    'priceChart.insiderTrade': 'インサイダー取引',
    'priceChart.movement': '取引以降の価格変動',
    'priceChart.increased': '価格上昇',
    'priceChart.decreased': '価格下落',
    'priceChart.tradePriceLabel': '取引価格:',
    'priceChart.currentLabel': '現在:',

    // Ranking page
    'ranking.title': 'トップ買い推奨',
    'ranking.subtitle': 'インサイダー取引パターンに基づくAI株式推奨',
    'ranking.topStocks': '推奨株式トップ10',
    'ranking.recommendation': '推奨',
    'ranking.buyPotential': '買いポテンシャル',
    'ranking.marketCap': '時価総額',
    'ranking.volume': '取引量',
    'ranking.priceChange': '価格変動',
    'ranking.lastPrice': '現在価格',
    'ranking.strongBuy': '強い買い',
    'ranking.buy': '買い',
    'ranking.hold': 'ホールド',
    'ranking.analysis': '分析',
    'ranking.insiderActivity': 'インサイダー活動',
    'ranking.tradesLast30Days': '過去30日の取引',
    'ranking.avgTradeValue': '平均取引価値',
    'ranking.netBuying': 'ネット買い',
    'ranking.loading': '株式ランキングを読み込み中...',
    'ranking.noData': 'ランキングデータがありません',
    'ranking.refreshData': 'データを更新',

    // Not Found page
    'notFound.title': '404 - ページが見つかりません',
    'notFound.message': 'お探しのページは存在しません。',
  },
  zh: {
    // Navigation
    'nav.dashboard': '仪表盘',
    'nav.livetrading': '实时交易',
    'nav.analytics': '分析',
    'nav.alerts': '提醒',
    'nav.search': '搜索',
    'nav.ranking': '热门股票',
    'nav.settings': '设置',
    
    // Dashboard
    'dashboard.title': '内幕交易追踪专业版',
    'dashboard.subtitle': 'AI驱动的内幕交易监控器',
    'dashboard.lastUpdated': '最后更新',
    'dashboard.stats.todayTrades': '今日交易',
    'dashboard.stats.totalVolume': '总交易量',
    'dashboard.recentActivity': '最近活动',
    'dashboard.marketCoverage': '市场覆盖',
    'dashboard.topMoversToday': '今日热门股',
    
    // Trades
    'trades.loadingStats': '正在加载交易统计...',
    'trades.failedStats': '加载交易统计失败。请刷新页面。',
    'trades.recentTrades': '最近的内幕交易',
    'trades.loadingTrades': '正在加载交易...',
    'trades.viewDetails': '查看详情',
    'trades.loadMore': '加载更多交易',
    'trades.noTrades': '没有可用的交易',
    'trades.company': '公司',
    'trades.shares': '股份',
    'trades.price': '价格',
    'trades.total': '总价值',
    'trades.signal': '信号',
    'trades.significance': '重要性',
    'trades.filed': '提交日期',
    
    // Settings
    'settings.title': '设置',
    'settings.language': '语言',
    'settings.theme': '主题',
    'settings.notifications': '通知',
    'settings.language.english': '英语',
    'settings.language.korean': '韩语',
    'settings.language.japanese': '日语',
    'settings.language.chinese': '中文',
    'settings.theme.light': '浅色',
    'settings.theme.dark': '深色',
    'settings.theme.system': '系统',
    'settings.description': '管理您的应用程序偏好和设置。',
    'settings.themeDescription': '选择您喜欢的主题',
    'settings.notificationsFuture': '通知设置将在未来更新中提供。',
    
    // WebSocket Status
    'websocket.connected': '已连接到实时推送',
    'websocket.disconnected': '实时推送已断开',
    'websocket.connecting': '正在连接到实时推送...',
    
    // General
    'general.loading': '加载中...',
    'general.error': '错误',
    'general.success': '成功',
    'general.refresh': '刷新',
    'general.save': '保存',
    'general.cancel': '取消',
    'general.delete': '删除',
    
    // Page specific
    'page.dashboard.subtitle': '实时内幕交易监控和市场情报',
    'page.livetrading.title': '实时交易',
    'page.livetrading.subtitle': '带AI分析的实时内幕交易活动',
    'page.search.placeholder': '搜索公司、股票代码、交易员或职位...',
    'page.alerts.title': '智能提醒',
    'page.alerts.subtitle': '为内幕交易活动设置智能提醒',
    'page.analytics.title': '市场分析',
    'page.analytics.subtitle': '内幕交易模式的综合分析',
    
    // WebSocket and Connection
    'connection.liveFeedActive': '实时数据推送已激活 - 实时SEC文件监控',
    'connection.connectionLost': '连接已断开 - 正在尝试重新连接...',
    'connection.liveFeed': '实时推送',
    'connection.disconnected': '已断开',
    
    // Statistics and Data
    'stats.todayTrades': '今日交易',
    'stats.totalVolume': '总交易量',
    'stats.tradingSummary': '交易摘要',
    'stats.failedLoad': '加载交易统计失败。请刷新页面。',
    'stats.fromLastWeek': '与上周相比',
    
    // Filters and Search
    'filter.allTypes': '所有类型',
    'filter.buyOrders': '买入订单',
    'filter.sellOrders': '卖出订单',
    'filter.allSignals': '所有信号',
    'filter.buySignal': '买入信号',
    'filter.sellSignal': '卖出信号',
    'filter.holdSignal': '持有信号',
    'filter.buyOnly': '仅买入',
    'filter.sellOnly': '仅卖出',
    
    // Placeholders
    'placeholder.searchCompany': '搜索公司...',
    'placeholder.searchTrader': '搜索交易员...',
    'placeholder.noLimit': '无限制',
    'placeholder.preferredLanguage': '选择您的首选语言',
    
    // Alert types
    'alerts.type.volume': '交易量',
    'alerts.type.company': '公司名称',
    'alerts.type.trader': '交易员职位',
    
    // Search page
    'search.title': '搜索和筛选',
    'search.subtitle': '使用高级条件搜索和筛选内幕交易数据',
    'search.filters': '筛选器',
    'search.clear': '清除',
    'search.tradeType': '交易类型',
    'search.dateRange': '日期范围',
    'search.sortBy': '排序方式',
    'search.dateRange.all': '全部时间',
    'search.dateRange.7d': '过去7天',
    'search.dateRange.30d': '过去30天',
    'search.dateRange.90d': '过去90天',
    'search.sort.recent': '最新',
    'search.sort.value': '金额最高',
    'search.sort.company': '公司名称',
    'search.results': '结果',
    'search.buyTrades': '买入交易',
    'search.sellTrades': '卖出交易',
    'search.totalVolume': '总交易量',
    'search.companies': '公司',
    'search.traders': '交易员',
    'search.totalFound': '找到的总交易数',
    'search.combinedValue': '综合价值',
    'search.uniqueEntities': '独特实体',
    'search.uniqueInsiders': '独特内幕人士',
    'search.searchResults': '搜索结果',
    'search.noTrades': '未找到交易',
    'search.placeholder.minValue': '1000000',
    'search.value': '最小值',
    
    // Alerts page
    'alerts.title': '智能提醒',
    'alerts.subtitle': '为内幕交易活动设置智能提醒',
    'alerts.active': '活动提醒',
    'alerts.createNew': '创建新提醒',
    'alerts.alertName': '提醒名称',
    'alerts.alertType': '提醒类型',
    'alerts.condition': '条件',
    'alerts.value': '值',
    'alerts.paused': '暂停',
    'alerts.noAlerts': '尚未配置提醒',
    'alerts.createFirst': '在下方创建您的第一个提醒',
    'alerts.noMatches': '最近没有匹配',
    'alerts.setupMatches': '设置提醒以在此查看匹配',
    'alerts.condition.greaterThan': '大于',
    'alerts.condition.lessThan': '小于',
    'alerts.condition.equals': '等于',
    'alerts.condition.contains': '包含',
    'alerts.placeholder.name': '例如：大型苹果交易',
    'alerts.recentMatches': '最近匹配',
    
    // Live Trading page
    'liveTrading.filtersAndSearch': '筛选器和搜索',
    'liveTrading.tradeType': '交易类型',
    'liveTrading.aiSignal': 'AI信号',
    'liveTrading.companyTicker': '公司/股票代码',
    'liveTrading.traderName': '交易员姓名',
    'liveTrading.minValue': '最小值 ($)',
    'liveTrading.maxValue': '最大值 ($)',
    'liveTrading.liveFeed': '实时交易推送',
    'liveTrading.tradesShown': '显示的交易',
    'liveTrading.noTrades': '未找到交易',
    'liveTrading.adjustFilters': '尝试调整您的筛选器',
    'liveTrading.insider': '内幕人士',
    'liveTrading.tradeDetails': '交易详情',
    'liveTrading.totalValue': '总价值',
    'liveTrading.score': '评分:',
    'liveTrading.loadMore': '加载更多交易',
    'liveTrading.activeNow': '当前活跃',
    'liveTrading.alertsSet': '提醒设置',
    'liveTrading.pageTitle': '所有交易显示与搜索',
    'liveTrading.pageTitleMobile': '交易搜索',
    'liveTrading.pageSubtitle': '搜索和过滤所有内幕交易数据',
    'liveTrading.totalTrades': '总计',
    'liveTrading.filtered': '已过滤',
    'liveTrading.realtimeStock': '实时股价',
    'liveTrading.loaded': '已加载',
    'liveTrading.loading': '加载中',
    'liveTrading.dataQuality': '数据质量',
    'liveTrading.issues': '个问题',
    'liveTrading.loadingTrades': '正在加载交易数据...',
    'liveTrading.alert': '提醒',
    'liveTrading.watchlist': '关注列表',
    'liveTrading.added': '已添加',
    'liveTrading.watch': '关注',
    'liveTrading.advancedAiAnalysis': '高级AI分析',
    'liveTrading.confidenceLevel': '置信度',
    'liveTrading.advancedAnalyzing': '高级AI分析中...',
    'liveTrading.realtimePriceInfo': '实时价格信息',
    'liveTrading.insiderTradePrice': '内幕人士交易价格',
    'liveTrading.expectedImpact': '预期影响',
    'liveTrading.similarTrades': '相似交易',
    'liveTrading.count': '笔',
    'liveTrading.pieces': '个',
    'liveTrading.analysisInProgress': '正在综合分析新闻、财务数据和内幕人士模式',
    'liveTrading.basicAnalysis': '基础分析',
    'liveTrading.loadingTradeData': '正在加载交易数据...',
    'liveTrading.fetchingLatestInsider': '正在获取最新内幕交易信息',
    'liveTrading.avgLoadingTime': '💡 平均加载时间: 3-5秒',
    'liveTrading.remaining': '个剩余',
    'liveTrading.myWatchlist': '我的关注列表',
    'liveTrading.addToWatchlist': '添加到关注列表',
    'liveTrading.emailAlerts': '邮件提醒',
    'liveTrading.smartAlerts': '智能提醒',
    'liveTrading.watchlistAdded': '已添加到关注列表',
    'liveTrading.realtimeAlertsAvailable': '也可以设置实时提醒',
    'liveTrading.getRealtimeAlerts': '接收实时交易提醒',
    'liveTrading.alertEmail': '提醒接收邮箱',
    'liveTrading.alertConditions': '提醒条件',
    'liveTrading.successfullyAdded': '成功添加!',
    'liveTrading.additionComplete': '添加完成!',
    'liveTrading.canViewSeparately': '的内幕交易信息可以单独查看',
    'liveTrading.viewWatchlist': '查看关注列表',
    'liveTrading.whenInsiderTrade': '内幕交易发生时',
    'liveTrading.whenPriceChange': '股价大幅波动时',
    'liveTrading.whenVolumeSpike': '交易量激增时',
    'liveTrading.largeTrades': '大额交易 ($10M+)',
    'liveTrading.whenRecommendedPrice': '达到推荐买入价格时',
    'liveTrading.dataQualityReport': '数据质量报告',
    'liveTrading.validTrades': '有效交易',
    
    // Trade Card
    'tradeCard.filed': '已提交',
    'tradeCard.shares': '股数',
    'tradeCard.avgPrice': '平均价格',
    'tradeCard.totalValue': '总价值',
    'tradeCard.ownership': '所有权',
    'tradeCard.details': '详情',
    
    // Trade List
    'tradeList.recentTrades': '最近内幕交易',
    'tradeList.searchCompanies': '搜索公司...',
    'tradeList.sort': '排序:',
    'tradeList.date': '日期',
    'tradeList.value': '价值',
    'tradeList.noTradesFound': '未找到符合您条件的交易。',
    'tradeList.loading': '加载中...',
    'tradeList.loadMore': '加载更多交易',
    'tradeList.noMatches': '未找到符合您条件的交易。',
    'tradeList.searchPlaceholder': '搜索公司...',
    
    // Dashboard Stats
    'dashboardStats.todayTrades': '今日交易',
    'dashboardStats.totalVolume': '总交易量',
    'dashboardStats.fromLastWeek': '与上周相比',
    'dashboardStats.recentActivity': '最近活动',
    'dashboardStats.monitoring': '监控所有主要交易所的内幕交易',
    'dashboardStats.marketCoverage': '市场覆盖',
    'dashboardStats.realTimeAnalysis': '实时SEC文件分析和交易分类',
    'dashboardStats.topMovers': '今日热门',
    
    // Analytics page
    'analytics.subtitle': '全面的内幕交易市场分析和洞察',
    'analytics.totalTrades': '总交易数',
    'analytics.transactionsRecorded': '记录的内幕交易',
    'analytics.totalVolume': '总交易量',
    'analytics.combinedValue': '综合交易价值',
    'analytics.avgTradeSize': '平均交易规模',
    'analytics.averageValue': '平均交易价值',
    'analytics.companies': '公司',
    'analytics.uniqueTracked': '跟踪的独特公司',
    'analytics.tradeDistribution': '交易类型分布',
    'analytics.monthlyActivity': '月度交易活动',
    'analytics.topCompanies': '按交易量排名的顶级公司',
    'analytics.trades': '交易',
    'analytics.combinedTransactionValue': '综合交易价值',
    'analytics.averageTransactionValue': '平均交易价值',
    'analytics.uniqueCompaniesTracked': '跟踪的独特公司',
    'analytics.tradeTypeDistribution': '交易类型分布',
    'analytics.monthlyTradingActivity': '月度交易活动',
    'analytics.topCompaniesByVolume': '按交易量排名的顶级公司',
    'analytics.buys': '买入',
    'analytics.sells': '卖出',
    
    // Trade Detail page
    'tradeDetail.notFound': '未找到交易',
    'tradeDetail.notFoundMessage': '无法找到请求的交易。',
    'tradeDetail.backToDashboard': '返回仪表盘',
    'tradeDetail.back': '返回',
    'tradeDetail.title': '交易详情',
    'tradeDetail.companyInfo': '公司信息',
    'tradeDetail.company': '公司',
    'tradeDetail.tickerSymbol': '股票代码',
    'tradeDetail.tradeType': '交易类型',
    'tradeDetail.traderInfo': '交易员信息',
    'tradeDetail.name': '姓名',
    'tradeDetail.titlePosition': '职位/地位',
    'tradeDetail.ownership': '所有权',
    'tradeDetail.transactionDetails': '交易详情',
    'tradeDetail.sharesTraded': '交易股数',
    'tradeDetail.pricePerShare': '每股价格',
    'tradeDetail.totalValue': '总交易价值',
    'tradeDetail.filingDate': '提交日期',
    'tradeDetail.currentPrice': '当前股价',
    'tradeDetail.volume': '交易量',
    'tradeDetail.lastUpdated': '最后更新',
    'tradeDetail.analysis': '详细分析',
    'tradeDetail.priceComparison': '价格比较',
    'tradeDetail.tradePrice': '交易价格：',
    'tradeDetail.currentPriceLabel': '当前价格：',
    'tradeDetail.perShareComparison': '每股比较',
    'tradeDetail.secFiling': 'SEC文件 #',
    'tradeDetail.totalTransactionValue': '总交易价值',
    'tradeDetail.currentStockPrice': '当前股价',
    'tradeDetail.detailedAnalysis': '详细分析',
    'tradeDetail.actualTradePrice': '实际交易价格',
    'tradeDetail.insiderAvgPrice': '内幕人士平均交易价格',
    'tradeDetail.last30DaysAvg': '过去30天平均',
    'tradeDetail.sameTicker': '同股票代码平均',
    'tradeDetail.currentMarketPrice': '当前市场价格',
    'tradeDetail.realtimeEstimate': '实时估价',
    'tradeDetail.marketClosed': '休市（最近价格）',
    'tradeDetail.realtimePrice': '实时价格',
    'tradeDetail.lastClosePrice': '最后收盘价（休市中）',
    'tradeDetail.aiAnalysisResults': 'AI分析结果',
    'tradeDetail.tradingPatternAnalysis': '交易模式分析',
    'tradeDetail.investmentStrategy': '投资策略',
    'tradeDetail.additionalInsights': '额外洞察',
    
    // Price Comparison Chart
    'priceChart.title': '价格比较图表',
    'priceChart.tradePrice': '交易价格',
    'priceChart.currentPrice': '当前价格',
    'priceChart.today': '今天',
    'priceChart.insiderTrade': '内幕交易',
    'priceChart.movement': '交易后价格变动',
    'priceChart.increased': '价格上涨',
    'priceChart.decreased': '价格下跌',
    'priceChart.tradePriceLabel': '交易价格：',
    'priceChart.currentLabel': '当前：',

    // Ranking page
    'ranking.title': '热门买入推荐',
    'ranking.subtitle': '基于内幕交易模式的AI股票推荐',
    'ranking.topStocks': '推荐股票前10名',
    'ranking.recommendation': '推荐',
    'ranking.buyPotential': '买入潜力',
    'ranking.marketCap': '市值',
    'ranking.volume': '交易量',
    'ranking.priceChange': '价格变动',
    'ranking.lastPrice': '当前价格',
    'ranking.strongBuy': '强烈买入',
    'ranking.buy': '买入',
    'ranking.hold': '持有',
    'ranking.analysis': '分析',
    'ranking.insiderActivity': '内幕人士活动',
    'ranking.tradesLast30Days': '过去30天交易',
    'ranking.avgTradeValue': '平均交易价值',
    'ranking.netBuying': '净买入',
    'ranking.loading': '正在加载股票排名...',
    'ranking.noData': '没有排名数据',
    'ranking.refreshData': '刷新数据',

    // Not Found page
    'notFound.title': '404 - 页面未找到',
    'notFound.message': '您要查找的页面不存在。',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    // Check localStorage for saved language first (user preference takes priority)
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      console.log('🌍 Using saved language preference:', savedLanguage);
      setLanguage(savedLanguage);
      return; // Exit early - user preference overrides browser detection
    }
    
    // Only detect browser language if no saved preference exists
    const browserLang = navigator.language.toLowerCase();
    console.log('🌍 No saved language, detecting browser language:', browserLang);
    
    if (browserLang.startsWith('ko')) {
      setLanguage('ko');
    } else if (browserLang.startsWith('ja')) {
      setLanguage('ja');
    } else if (browserLang.startsWith('zh')) {
      setLanguage('zh');
    } else {
      setLanguage('en');
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const currentTranslations = translations[language] as Record<string, string>;
    const fallbackTranslations = translations.en as Record<string, string>;
    return currentTranslations[key] || fallbackTranslations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};